// Copyright (c) Microsoft. All rights reserved.

#ifndef IFABRICZZZZ_H
#define IFABRICZZZZ_H

#include "windows.h"

/*the below typedefs (2) and the struct are "how they would be generated by the idl compiler"*/
typedef struct IFabricZZZZ IFabricZZZZ;

typedef struct IFabricZZZZVtbl
{
    ULONG(STDMETHODCALLTYPE* Release)(
        IFabricZZZZ* This);

    HRESULT(STDMETHODCALLTYPE* DoSomethingAwesome)(
        IFabricZZZZ* This,
        /* [in] */ const char* queryDescription,
        /* [in] */ DWORD timeoutMilliseconds
        );

    HRESULT(STDMETHODCALLTYPE* DoSomethingAwesomeNoSFTimeout)(
        IFabricZZZZ* This,
        /* [in] */ const char* queryDescription
        );

    HRESULT(STDMETHODCALLTYPE* DoSomethingWithPossibleFailures)(
        IFabricZZZZ* This,
        /* [in] */ const char* queryDescription,
        /* [in] */ DWORD timeoutMilliseconds
        );

    HRESULT(STDMETHODCALLTYPE* DoSomethingWithPossibleFailuresNoSFTimeout)(
        IFabricZZZZ* This,
        /* [in] */ const char* queryDescription
        );

} IFabricZZZZVtbl;

struct IFabricZZZZ
{
    CONST_VTBL struct IFabricZZZZVtbl* lpVtbl;
};

#endif /*IFABRICZZZZ_H*/
