//
// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
//

import "unknwn.idl";
import "FabricCommon.idl";

//=====================================================================================================================
// Forward declarations
interface ITestAsyncOperation;

//=====================================================================================================================
// ITestAsyncOperation
//=====================================================================================================================
[
    uuid(5F5898FA-7BB0-49F0-81D1-7CBFF5FCFF55),
    version(1.0),
    local
]
interface ITestAsyncOperation : IUnknown
{
    HRESULT BeginTestOperation(int arg1, IFabricAsyncOperationCallback* callback, IFabricAsyncOperationContext** context);
    HRESULT EndTestOperation(IFabricAsyncOperationContext* context, int* operation_result);
    HRESULT BeginTestOperationWithNoBeginArgs(IFabricAsyncOperationCallback* callback, IFabricAsyncOperationContext** context);
    HRESULT EndTestOperationWithNoBeginArgs(IFabricAsyncOperationContext* context, int* operation_result_1, double* operation_result_2);
    HRESULT BeginTestOperationWithNoEndArgs(int arg1, IFabricAsyncOperationCallback* callback, IFabricAsyncOperationContext** context);
    HRESULT EndTestOperationWithNoEndArgs(IFabricAsyncOperationContext* context);
    HRESULT BeginTestOperationWithNoArgs(IFabricAsyncOperationCallback* callback, IFabricAsyncOperationContext** context);
    HRESULT EndTestOperationWithNoArgs(IFabricAsyncOperationContext* context);
};
