// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

#include "sf_c_util_reals_ut_pch.h"

BEGIN_TEST_SUITE(TEST_SUITE_NAME_FROM_CMAKE)

// this test makes sure that the mappings work
// (there is a real_ function corresponding to the original)
TEST_FUNCTION(check_sf_c_util_reals) // no-srs
{
    // arrange
    // act
    REGISTER_HRESULT_TO_STRING_GLOBAL_MOCK_HOOK();
    REGISTER_FABRIC_CONFIGURATION_PARAMETER_ARGC_ARGV_GLOBAL_MOCK_HOOK();
    REGISTER_FABRIC_CONFIGURATION_PARAMETER_LIST_ARGC_ARGV_GLOBAL_MOCK_HOOK();
    REGISTER_FABRIC_CONFIGURATION_SECTION_ARGC_ARGV_GLOBAL_MOCK_HOOK();
    REGISTER_FABRIC_CONFIGURATION_SECTION_LIST_ARGC_ARGV_GLOBAL_MOCK_HOOK();
    REGISTER_COMMON_ARGC_ARGV_GLOBAL_MOCK_HOOK();
    REGISTER_FABRIC_CONFIGURATION_PACKAGE_GLOBAL_MOCK_HOOK();
    REGISTER_FABRIC_CONFIGURATION_ACTIVATION_CONTEXT_GLOBAL_MOCK_HOOK();
    REGISTER_FABRIC_STRING_RESULT_GLOBAL_MOCK_HOOK();
    REGISTER_FABRIC_STRING_LIST_RESULT_GLOBAL_MOCK_HOOK();
    REGISTER_FABRIC_ENDPOINT_RESOURCE_DESCRIPTION_ARGC_ARGV_GLOBAL_MOCK_HOOK();
    REGISTER_FABRIC_ENDPOINT_RESOURCE_DESCRIPTION_LIST_ARGC_ARGV_GLOBAL_MOCK_HOOK();


    // assert
    // no explicit assert, if it builds it works
}

END_TEST_SUITE(TEST_SUITE_NAME_FROM_CMAKE)
